### ISSUE TITLE
[Bug?] No `Respondable` instance for `HTMLDocument`?

### ISSUE THREAD

**Issue by fosskers** [purescript-contrib/purescript-affjax#110]
I have a servant endpoint that yields some HTML:
```haskell
type API = ...
  :<|> "xhrtest" :> Get '[HTML] (Html ())
...
```
and a little testing function in my Purescript that looks like:
```purescript
xhrtest :: forall e. Aff ( ajax :: AJAX, console :: CONSOLE | e ) Document
xhrtest = do
  log "Before..."
  res <- get "/xhrtest"
  log "After!"
  pure res.response
```
but when called, I see this in my console:
```
Before...
Error: (NonEmptyList (NonEmpty (TypeMismatch "Document" "HTMLDocument") Nil))
```
And unfortunately setting the return type of `xhrtest` to give an `HTMLDocument` instead yields the following:
```
  No type class instance was found for
  
    Network.HTTP.Affjax.Response.Respondable HTMLDocument
```
Which I believe, having seen the module docs. So, is this a case of a missing instance of `Respondable`? If not, where is my mistake? I'm happy with any return type, so long as it allows me to use [appendChild](https://pursuit.purescript.org/packages/purescript-dom-classy/2.1.0/docs/DOM.Classy.Node#v:appendChild) from `dom-classy`.

Thoughts? Please and thanks.

**Comment by kRITZCREEK** [comment]
How about accepting the data as a String, and using something like https://github.com/toastal/purescript-domparser to parse the String into a Document? You might need to do some coercion between Document and HTMLDocument, I don't really know the difference in the DOM API terms.

**Comment by fosskers** [comment]
`Document` is closer to what I actually need, so this function is probably right up my alley:
```
parseHTMLFromString :: String -> DOMParser -> Document
```

**Comment by kRITZCREEK** [comment]
Can't be a good API if it's part of the DOM spec, right? 😞 

From https://developer.mozilla.org/en-US/docs/Web/API/DOMParser
> Note that if the parsing process failed, the DOMParser does not throw an exception, but instead returns an error document:
