### ISSUE TITLE
Provide an option for configuring `xhr.timeout`

### ISSUE THREAD

**Issue by paluh** [purescript-contrib/purescript-affjax#143]
It seems that both xhr2 and browsers support a `timeout` option. Should I provide a PR which adds this option to the `Request` (I mean `timeout :: Milliseconds`) type?

**Comment by chekoopa** [comment]
Affjax previously has `timeout` parameter as a part of `RetryPolicy`, which was mistakenly removed with [d710d92a46f8afb165214be07d452fd586c78c0d] (@garyb, you weren't right, we are using them actively to control backend connections, even retries). 

So, yes, that PR would be pretty neat.

**Comment by chekoopa** [comment]
Bump. :confused:
