### ISSUE TITLE
purescript-affjax v10.1.0 isn't published on Pursuit

### ISSUE THREAD

**Issue by elliotdavies** [purescript-contrib/purescript-affjax#149]
Caused me some minor confusion when the latest docs still included `ResponseFormatError` but my code couldn't find it 😁

**Comment by thomashoneyman** [comment]
It's up on Pursuit! https://pursuit.purescript.org/packages/purescript-affjax/10.1.0

So is the latest release: https://pursuit.purescript.org/packages/purescript-affjax/11.0.0
