### ISSUE TITLE
Pursuit is not up to date

### ISSUE THREAD

**Issue by cscalfani** [purescript-contrib/purescript-affjax#152]
Just recently used this library with `spago` and the version I get appears to be the latest, i.e. `10.0.2`, but `Pursuit` still only shows version `10.0.0`.

This isn't normally a big deal but `ResponseFormatError` is documented in `Pursuit`, but has been removed making it very difficult for people to figure what's the right way to upgrade old code.

I had to look at the source code. Not terrible, but would be nicer if `Pursuit` was up to date.

**Comment by thomashoneyman** [comment]
Sorry about that! I've uploaded the latest release (`v11.0.0`) to Pursuit, as well as the previous release, `v10.1.0`.

https://pursuit.purescript.org/packages/purescript-affjax/11.0.0

**Comment by cscalfani** [comment]
Thanks!!
