### ISSUE TITLE
Query Issues with React Native

### ISSUE THREAD

**Issue by kodeFant** [purescript-contrib/purescript-affjax#163]
Hi, I am currently using affjax in a React Native environment. More specifically with [React.Basic.Native](https://github.com/f-f/purescript-react-basic-native). I also installed `xhr2` to be sure. I know React Native primarily supports the `fetch` api.

**Describe the bug**
Fetching from a simple enpoint work well, but all query parameters are ignored.

I first tried it like this with query string in URL

```purescript
getProductComments :: Product -> Aff (RemoteData String (Array Comment))
getProductComments product = do
  res <-
    AX.request
      ( AX.defaultRequest
          { url = apiUrl <> "/ProductComments?productId=" <> product.id
          , method = Left GET
          , responseFormat = ResponseFormat.json
          , headers = unauthenticatedHeaders
          }
      )
  pure (responseToRemoteData res decodeComments)
```

It seems to strip away the query parameters and only the query without any params are run.

Same thing actually happens when using a response body only. 

```purescript
getProductComments :: Product -> Aff (RemoteData String (Array Comment))
getProductComments product = do
  res <-
    AX.request
      ( AX.defaultRequest
          { url = apiUrl <> "/ProductComments"
          , method = Left GET
          , responseFormat = ResponseFormat.json
          , content = Just (RequestBody.json $ encodeJson { productId: product.id })
          , headers = unauthenticatedHeaders
          }
      )
  pure (responseToRemoteData res decodeComments)
```

The API supports both query params and body params and I have tested this on postman and can verify it works. 

**Expected behavior**
Query strings should be registered and not stripped away.

**Additional context**
- Brief discussion on **#purescript-beginners** on Slack highligthing some theories about whether it's regarding the environment it chooses: https://functionalprogramming.slack.com/archives/C717K38CE/p1626869787068100
- Networking in React Native: https://reactnative.dev/docs/network
- React Native JavaScript environment: https://reactnative.dev/docs/javascript-environment

**Comment by garyb** [comment]
I don't know anything about React Native, and very little about `fetch` too, so hopefully someone else can chime in here who has ideas. :smile:

One option might be to avoid this library and use [purescript-web-fetch](https://github.com/purescript-web/purescript-web-fetch) directly or something like that.

**Comment by kodeFant** [comment]
Thanks for reply :) Closing the issue since I am solving the problems elsewhere.
